version: '2'

services:
  hotel-mysql:
    container_name: hotel-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  hotel-app:
    container_name: hotel-app
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes: 
      - /Users/i349201/Documents/projects/hotel_booking/source_code:/app
    depends_on:
      - hotel-mysql
    ports:
      - "8181:8181"
    restart: always
